version: '3'

services:
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  db:
    image: postgres

  redis:
    restart: always
    image: redis:latest
    privileged: true
    command: bash -c "sysctl vm.overcommit_memory=1 && redis-server"
    ports:
      - "6379:6379"
