# Generated by Django 2.2.5 on 2019-09-19 12:25

from django.conf import settings
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название фильма')),
            ],
        ),
        migrations.CreateModel(
            name='ViewsMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_view', models.PositiveSmallIntegerField(default=1, verbose_name='Кол-во просмотров')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='recommendations.Movie')),
                ('user', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='viewsmovie',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['timestamp'], name='recommendat_timesta_e6ef46_brin'),
        ),
        migrations.AlterUniqueTogether(
            name='viewsmovie',
            unique_together={('user', 'movie')},
        ),
    ]
